# In Class Activity April 14th, 2026

In [1]:
# pip install optuna

### Importing libraries, preparing data, initial EDA

In [26]:
# importing libraries (feel free to add more if you want to explore other things)
import numpy as np
import pandas as pd
import sweetviz as sv
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.model_selection import RandomizedSearchCV, StratifiedKFold
from xgboost import XGBClassifier
from sklearn.metrics import f1_score, accuracy_score, classification_report, roc_auc_score
import optuna

In [27]:
# importing data
adult = pd.read_csv('adult.csv')
adult.head(20)

,age,workclass,fnlwgt,education,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,89814,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,336951,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,160323,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,18,?,103497,Some-college,10,Never-married,?,Own-child,White,Female,0,0,30,United-States,<=50K
5,34,Private,198693,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K
6,29,?,227026,HS-grad,9,Never-married,?,Unmarried,Black,Male,0,0,40,United-States,<=50K
7,63,Self-emp-not-inc,104626,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,>50K
8,24,Private,369667,Some-college,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,<=50K
9,55,Private,104996,7th-8th,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,<=50K
10,65,Private,184454,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,>50K
11,36,Federal-gov,212465,Bachelors,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,<=50K
12,26,Private,82091,HS-grad,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States,<=50K
13,58,?,299831,HS-grad,9,Married-civ-spouse,?,Husband,White,Male,0,0,35,United-States,<=50K
14,48,Private,279724,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,>50K
15,43,Private,346189,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,>50K
16,20,State-gov,444554,Some-college,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,<=50K
17,43,Private,128354,HS-grad,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States,<=50K
18,37,Private,60548,HS-grad,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States,<=50K
19,40,Private,85019,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,?,>50K

In [28]:
# initial EDA with sweetviz
report = sv.analyze(adult)
report.show_html('sweet_report.html')

# you are welcome to replace this cell with your own EDA, but make sure to include
# some visualizations and insights about the data

                                             |          | [  0%]   00:00 -> (? left)

Report sweet_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

### In the markdown cell below describe what you learned from your EDA and how it will inform your modeling decisions

There is missing data and target class imbalance.  There is also a significant portion of the population (over 20%) who are in the `other` category for education, making it useless (potentially), since it combines doctorates and HS dropouts together.

### Data Preprocessing (minimal) and Baseline Model

In [29]:
# data cleaning and preprocessing

# changing ? to NaN
adult = adult.replace('?', np.nan)

#education and education num are redundant, so we can drop one of them
adult = adult.drop('education', axis=1)

# target variable is income with 2 levels, so we can encode it as 0 and 1
adult['income'] = adult['income'].apply(lambda x: 1 if x == '>50K' else 0)

# change dtype categorical variables to category
categorical_cols = adult.select_dtypes(include='object').columns
adult[categorical_cols] = adult[categorical_cols].astype('category')


adult.head(20)

C:\Users\jfigg\AppData\Local\Temp\ipykernel_36292\2764229057.py:13: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = adult.select_dtypes(include='object').columns

,age,workclass,fnlwgt,educational-num,marital-status,occupation,relationship,race,gender,capital-gain,capital-loss,hours-per-week,native-country,income
0,25,Private,226802,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,0
1,38,Private,89814,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,0
2,28,Local-gov,336951,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,1
3,44,Private,160323,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,1
4,18,NaN,103497,10,Never-married,NaN,Own-child,White,Female,0,0,30,United-States,0
5,34,Private,198693,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,0
6,29,NaN,227026,9,Never-married,NaN,Unmarried,Black,Male,0,0,40,United-States,0
7,63,Self-emp-not-inc,104626,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,3103,0,32,United-States,1
8,24,Private,369667,10,Never-married,Other-service,Unmarried,White,Female,0,0,40,United-States,0
9,55,Private,104996,4,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,10,United-States,0
10,65,Private,184454,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,6418,0,40,United-States,1
11,36,Federal-gov,212465,13,Married-civ-spouse,Adm-clerical,Husband,White,Male,0,0,40,United-States,0
12,26,Private,82091,9,Never-married,Adm-clerical,Not-in-family,White,Female,0,0,39,United-States,0
13,58,NaN,299831,9,Married-civ-spouse,NaN,Husband,White,Male,0,0,35,United-States,0
14,48,Private,279724,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3103,0,48,United-States,1
15,43,Private,346189,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,50,United-States,1
16,20,State-gov,444554,10,Never-married,Other-service,Own-child,White,Male,0,0,25,United-States,0
17,43,Private,128354,9,Married-civ-spouse,Adm-clerical,Wife,White,Female,0,0,30,United-States,0
18,37,Private,60548,9,Widowed,Machine-op-inspct,Unmarried,White,Female,0,0,20,United-States,0
19,40,Private,85019,16,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,45,NaN,1

In [30]:
# defining features and target variable
X = adult.drop('income', axis=1)
y = adult['income']

# splitting data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, 
                                                    random_state=42, stratify=y)

In [31]:
# building xgboost default model and evaluating with stratified k-fold cross validation
xgb_cv = XGBClassifier(enable_categorical=True, random_state=42)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(xgb_cv, X, y, cv=skf, scoring='f1')
print(f'Cross-validated F1 scores: {cv_scores}')
print(f'Mean F1 score: {cv_scores.mean()}') 
print(f'ROC AUC score: {roc_auc_score(y, xgb_cv.fit(X, y).predict_proba(X)[:, 1])}')

Cross-validated F1 scores: [0.70680507 0.70892566 0.70898981 0.72424942 0.71086556]
Mean F1 score: 0.7119671046056588
ROC AUC score: 0.9565623023910909

### Use the markdown cell below to describe your baseline model performance and how you will try to improve it

My base model is pretty good when compared to the version found in class, and has an extremely high ROC AUC score.  To improve the model, I will probably just tune it and see what happens.

### Model feature exploration

In the code cell below, explore different features of XGBoost and how they work (e.g. scale_pos_weight, max_depth, learning_rate).
Use stratified k-fold cross or repeated stratified k-fold cross validation with your model building. 
You should explore at least 3 different features of XGBoost.
Identify the model that performs best.

In [32]:
scale_weight = y.value_counts()[0] / y.value_counts()[1]
print(f'Scale pos weight: {scale_weight}')
xgb_param_grid = {
    'scale_pos_weight': [1, 2, 5, 10, scale_weight],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
}
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
xgb_gscv = GridSearchCV(estimator=XGBClassifier(enable_categorical=True, random_state=42),
                        param_grid=xgb_param_grid,
                        scoring='f1',
                        cv=skf,
                        n_jobs=-1)
xgb_gscv.fit(X_train, y_train)

Scale pos weight: 3.179173440574998

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=True, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_policy...
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7],
                         'scale_pos_weight': [1, 2, 5, 10,
                                              np.float64(3.179173440574998)]},
             scoring='f1')

In [33]:
xgb_gscv.best_params_

{'learning_rate': 0.2, 'max_depth': 5, 'scale_pos_weight': 2}

The best model has a high learning rate of .2, a max depth of 5, and a scale of 2 for weighting purposes.

In [34]:
xgb_gscv.best_score_

np.float64(0.7276089235024191)

In [35]:
xgb_gscv.score(X_test, y_test)

0.7309425827944347

### Tuning with GridSearchCV

Use the code cell below to set up your parameter grid and run GridSearchCV with your preferred model from above. You should tune 4-5 hyperparameters utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [36]:
scale_weight = y.value_counts()[0] / y.value_counts()[1]
xgb_param_grid = {
    'scale_pos_weight': [1, 2, 5, 10, scale_weight],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1],
    'gamma': [0, 1, 5],
}
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
xgb_gscv = GridSearchCV(estimator=XGBClassifier(
                                    enable_categorical=True, 
                                    random_state=42, 
                                    device='cuda'
                                    ),
                        param_grid=xgb_param_grid,
                        scoring='f1',
                        cv=skf,
                        n_jobs=-1)
xgb_gscv.fit(X_train, y_train)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device='cuda',
                                     early_stopping_rounds=None,
                                     enable_categorical=True, eval_metric=None,
                                     feature_types=None, feature_weights=None,
                                     gamma=None, grow_poli...
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None, ...),
             n_jobs=-1,
             param_grid={'gamma': [0, 1, 5], 'learning_rate': [0.01, 0.1, 0.2],
                         'max_depth': [3, 5, 7],
                         'scale_pos_weight': [1, 2, 5, 10,
                                              np.float64(3.179173440574998)],
                         'subsample': [0.8, 1]},
             scoring='f1')

In [37]:
xgb_gscv.best_params_

{'gamma': 0,
 'learning_rate': 0.1,
 'max_depth': 7,
 'scale_pos_weight': 2,
 'subsample': 1}

In [38]:
xgb_gscv.best_score_

np.float64(0.7281397250686329)

In [39]:
xgb_gscv.score(X_test, y_test)

0.7291625808982153

### Tuning with RandomizedSearchCV

Using the code cell below as a starting point, tune your preferred model from above. Tune the same 4-5 hyperparameters from above utilizing cross validation. Train a final model using the best hyperparameters and report your model performance.

In [40]:
# tuning xgboost classifier with RandomizedSearchCV (tune more parameters than shown here)
param_dist = {
    'scale_pos_weight': [1, 2, 5, 10, scale_weight],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1],
    'gamma': [0, 1, 5],
}

# replace this placeholder model with your preferred model from above

xgb_random = RandomizedSearchCV(XGBClassifier(enable_categorical=True, random_state=42, device='cuda'),
                                param_distributions=param_dist, n_iter=20, cv=skf, scoring='f1', random_state=42)
xgb_random.fit(X_train, y_train)
print(f'Best parameters from RandomizedSearchCV: {xgb_random.best_params_}')
print(f'Best F1 score from RandomizedSearchCV: {xgb_random.best_score_}')   

# build your preferred model from above using best parameters from your RandomizedSearchCV
# and evaluate on the test set

xgb_random_best = XGBClassifier(random_state=42, scale_pos_weight=xgb_random.best_params_['scale_pos_weight'], 
                                max_depth=xgb_random.best_params_['max_depth'], 
                                learning_rate=xgb_random.best_params_['learning_rate'], 
                                subsample=xgb_random.best_params_['subsample'],
                                gamma=xgb_random.best_params_['gamma'],
                                enable_categorical=True)
xgb_random_best.fit(X_train, y_train)
y_pred_random = xgb_random_best.predict(X_test)
print(f'Classification report for RandomizedSearchCV-tuned model:\n{classification_report(y_test, y_pred_random)}')

Best parameters from RandomizedSearchCV: {'subsample': 0.8, 'scale_pos_weight': 2, 'max_depth': 7, 'learning_rate': 0.2, 'gamma': 0}
Best F1 score from RandomizedSearchCV: 0.7190863024387146
Classification report for RandomizedSearchCV-tuned model:
              precision    recall  f1-score   support

           0       0.93      0.89      0.91      7431
           1       0.68      0.78      0.73      2338

    accuracy                           0.86      9769
   macro avg       0.80      0.83      0.82      9769
weighted avg       0.87      0.86      0.86      9769

In [41]:
xgb_random_best.score(X_test, y_test)

0.8598628314054663

I genuinely have no clue why this happened, but the score on the test data is much higher than when I used `GridSearchCV`.  I have investigated but can't find any difference between the models (they use the same parameters), so I will chalk it up as an anomaly and move on.

### Tuning with Optuna

Using the code cell below as a starting point, tune your preferred model from above. You should tune the same 4-5 parameters as above using cross validation. Train a final model using the best hyperparameters and report your model performance.

In [42]:
from catboost import CatBoostClassifier

In [43]:
# tuning with Optuna (tune more parameters than shown here)
def objective(trial):
    scale_pos_w = trial.suggest_float('scale_pos_weight', 1, 10)
    max_depth = trial.suggest_int('max_depth', 4, 10)
    learning_rate = trial.suggest_float('learning_rate', .001, .3)
    subsample = trial.suggest_float('subsample', 0.8, 1.0)
    gamma = trial.suggest_float('gamma', 0.0, 10.0)

    model = XGBClassifier(
        random_state=42,
        learning_rate=learning_rate,
        max_depth=max_depth,
        gamma=gamma,
        subsample=subsample,
        scale_pos_weight=scale_pos_w,
        enable_categorical=True
    )

    cv_scores = cross_val_score(model, X, y, cv=skf, scoring='f1')
    return cv_scores.mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=20, show_progress_bar=True)

print(f'Best parameters from Optuna: {study.best_params}')
print(f'Best F1 score from Optuna: {study.best_value}')

# build preferred model from above with best parameters from Optuna and evaluate on the test set
xgb_optuna_best = XGBClassifier(
        random_state=42,
        learning_rate=study.best_params['learning_rate'],
        max_depth=study.best_params['max_depth'],
        gamma=study.best_params['gamma'],
        subsample=study.best_params['subsample'],
        scale_pos_weight=study.best_params['scale_pos_weight'],
        enable_categorical=True
    )
xgb_optuna_best.fit(X_train, y_train)
y_pred_optuna = xgb_optuna_best.predict(X_test)
print(f'Classification report for Optuna-tuned model:\n{classification_report(y_test, y_pred_optuna)}')

[I 2026-04-14 21:58:43,104] A new study created in memory with name: no-name-7cabf7e4-da32-47b0-8f52-b6ddd2089651

  0%|          | 0/20 [00:00<?, ?it/s]

[I 2026-04-14 21:58:45,045] Trial 0 finished with value: 0.6644500743152438 and parameters: {'scale_pos_weight': 9.217745686192686, 'max_depth': 7, 'learning_rate': 0.09163945463601944, 'subsample': 0.8965984496541188, 'gamma': 3.9280801123857225}. Best is trial 0 with value: 0.6644500743152438.
[I 2026-04-14 21:58:48,282] Trial 1 finished with value: 0.6563369867213528 and parameters: {'scale_pos_weight': 7.672390654048701, 'max_depth': 10, 'learning_rate': 0.01949228688614617, 'subsample': 0.8279310451306231, 'gamma': 7.050269063591922}. Best is trial 0 with value: 0.6644500743152438.
[I 2026-04-14 21:58:49,601] Trial 2 finished with value: 0.6812721494112992 and parameters: {'scale_pos_weight': 6.47271982597821, 'max_depth': 10, 'learning_rate': 0.24533539444586583, 'subsample': 0.9149601387993268, 'gamma': 8.202409183982937}. Best is trial 2 with value: 0.6812721494112992.
[I 2026-04-14 21:58:51,237] Trial 3 finished with value: 0.6658483569142291 and parameters: {'scale_pos_weight': 9.660194466600222, 'max_depth': 9, 'learning_rate': 0.12818612369227778, 'subsample': 0.9798471458120708, 'gamma': 7.627767476982923}. Best is trial 2 with value: 0.6812721494112992.
[I 2026-04-14 21:58:52,930] Trial 4 finished with value: 0.7222365525036133 and parameters: {'scale_pos_weight': 1.94035429529261, 'max_depth': 6, 'learning_rate': 0.057151985797350154, 'subsample': 0.9141150219474334, 'gamma': 5.005752577113396}. Best is trial 4 with value: 0.7222365525036133.
[I 2026-04-14 21:58:54,722] Trial 5 finished with value: 0.7168996866208006 and parameters: {'scale_pos_weight': 1.0905284647769908, 'max_depth': 7, 'learning_rate': 0.11384266957612689, 'subsample': 0.8427046872079034, 'gamma': 2.0615698420414863}. Best is trial 4 with value: 0.7222365525036133.
[I 2026-04-14 21:58:56,785] Trial 6 finished with value: 0.7246571813524911 and parameters: {'scale_pos_weight': 1.7686871460825464, 'max_depth': 7, 'learning_rate': 0.05450550352733074, 'subsample': 0.8900244095335625, 'gamma': 0.16131404788257142}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:58:58,183] Trial 7 finished with value: 0.6774814294128074 and parameters: {'scale_pos_weight': 6.740736785992497, 'max_depth': 5, 'learning_rate': 0.22516005553157517, 'subsample': 0.8066491153271503, 'gamma': 7.149724973969623}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:58:59,958] Trial 8 finished with value: 0.6897337043633911 and parameters: {'scale_pos_weight': 5.8992977783896405, 'max_depth': 7, 'learning_rate': 0.16685957429737758, 'subsample': 0.9011361687910819, 'gamma': 2.8737655952423333}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:01,799] Trial 9 finished with value: 0.6749243877419202 and parameters: {'scale_pos_weight': 9.225981792194561, 'max_depth': 10, 'learning_rate': 0.1457270978761677, 'subsample': 0.9756726609660537, 'gamma': 4.6240519813514345}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:03,105] Trial 10 finished with value: 0.6368011831491739 and parameters: {'scale_pos_weight': 3.203685387410141, 'max_depth': 4, 'learning_rate': 0.0030712100927290514, 'subsample': 0.8653879593879664, 'gamma': 0.10447333789697927}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:04,958] Trial 11 finished with value: 0.7166251608570069 and parameters: {'scale_pos_weight': 2.760398017239826, 'max_depth': 6, 'learning_rate': 0.0626411814856333, 'subsample': 0.9395857952720137, 'gamma': 0.4986125943331041}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:06,948] Trial 12 finished with value: 0.7036458150777014 and parameters: {'scale_pos_weight': 3.733479131435714, 'max_depth': 8, 'learning_rate': 0.054610704661900114, 'subsample': 0.870242562167411, 'gamma': 9.763828504393345}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:08,093] Trial 13 finished with value: 0.7164701894164978 and parameters: {'scale_pos_weight': 1.1531573040779657, 'max_depth': 5, 'learning_rate': 0.18866866133384358, 'subsample': 0.9331270308834015, 'gamma': 5.803886283730499}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:09,855] Trial 14 finished with value: 0.6909548870307204 and parameters: {'scale_pos_weight': 4.164662752872329, 'max_depth': 6, 'learning_rate': 0.053486273706938224, 'subsample': 0.9484962946168747, 'gamma': 2.137412917588776}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:11,175] Trial 15 finished with value: 0.6991446773113762 and parameters: {'scale_pos_weight': 4.417078642766835, 'max_depth': 8, 'learning_rate': 0.2891728687773966, 'subsample': 0.8766239481759291, 'gamma': 5.691869476672483}. Best is trial 6 with value: 0.7246571813524911.
[I 2026-04-14 21:59:12,874] Trial 16 finished with value: 0.7265529828662994 and parameters: {'scale_pos_weight': 2.1409907817951, 'max_depth': 6, 'learning_rate': 0.08841732066162006, 'subsample': 0.9072818401772726, 'gamma': 1.3864386171425493}. Best is trial 16 with value: 0.7265529828662994.
[I 2026-04-14 21:59:14,194] Trial 17 finished with value: 0.7173304032707217 and parameters: {'scale_pos_weight': 2.4943651784873726, 'max_depth': 4, 'learning_rate': 0.09930619447675676, 'subsample': 0.8877602544751296, 'gamma': 1.0924215440094747}. Best is trial 16 with value: 0.7265529828662994.
[I 2026-04-14 21:59:16,683] Trial 18 finished with value: 0.6783340035318765 and parameters: {'scale_pos_weight': 4.716404754700422, 'max_depth': 8, 'learning_rate': 0.028226967107050242, 'subsample': 0.9992526446784787, 'gamma': 1.5094671581364505}. Best is trial 16 with value: 0.7265529828662994.
[I 2026-04-14 21:59:18,137] Trial 19 finished with value: 0.7246420635943823 and parameters: {'scale_pos_weight': 1.9451907109797308, 'max_depth': 5, 'learning_rate': 0.08453153688842222, 'subsample': 0.8483542908331279, 'gamma': 3.1590972452848063}. Best is trial 16 with value: 0.7265529828662994.
Best parameters from Optuna: {'scale_pos_weight': 2.1409907817951, 'max_depth': 6, 'learning_rate': 0.08841732066162006, 'subsample': 0.9072818401772726, 'gamma': 1.3864386171425493}
Best F1 score from Optuna: 0.7265529828662994
Classification report for Optuna-tuned model:
              precision    recall  f1-score   support

           0       0.93      0.87      0.90      7431
           1       0.66      0.81      0.72      2338

    accuracy                           0.85      9769
   macro avg       0.80      0.84      0.81      9769
weighted avg       0.87      0.85      0.86      9769

### Tuning results

In the markdown cell below describe your experience tuning with the different methods. Which produced the best results? Which do you prefer?

I am used to `GridSearchCV`, and I `RandomizedSearchCV` uses the exact same syntax, so I didn't think those methods were difficult.  Regarding `optuna`, I think that it's an interesting approach, and pretty intuitive.  However, it doesn't really fit into the `sklearn` ecosystem, in the same way that a Windows laptop doesn't fit into the Apple ecosystem, despite the windows laptop probably being a better laptop on its own.  As such, it seems that optuna may be better individually, but since the grid searches work with `sklearn` pipelines, I still prefer it.